### ISSUE TITLE
Getting messages saying "Normal Flavor m1.small could not be found."

### ISSUE THREAD

**Issue by milliams** [dtantsur/rust-openstack#141]
If I run the code:
```rust
let flavor = os.get_flavor("m1.small").await?;
```
then it outputs the following to the screen:
```
Normal Flavor m1.small could not be found.
```
This is not an error being raised as the code continues to run, nor does it actually cause any problems as `flavor` gets populated correctly with all the details of the `m1.small` flavor.

If I pass in the string of the ID of the flavor (instead of the name) to `os.get_flavor` then the message is not printed.

I'm trying to track down where the message is coming from, but can't find it anywhere. I haven't turned on any logging and the message seems to appear on `stdout`.

I get the same thing if I create a server and specify the network by name `.with_network("external")`:
```
Normal Network external could not be found.
```

I'll note that fetching key pairs or images by name does not seem to trigger the message being printed.

I'm not sure why it has the prefix "Normal " or how to turn it off. Any pointers?

**Comment by milliams** [comment]
Your comment on "your logger" reminded me that in this demo project I was testing on, I didn't have a logger set up! I set up `env_logger` and set it to trace and I see the following (anonymised) snippet:

```
...
[2023-09-19T16:53:04Z TRACE osauth::client] Sending HTTP GET request to https://example.com:9696/v2.0/networks/external
Normal Network external could not be found.
[2023-09-19T16:53:04Z TRACE osauth::client] HTTP request returned 404 Not Found; error: Network external could not be found.
[2023-09-19T16:53:04Z TRACE openstack::network::api] Get network by name external
...
```

So you're right it's to do with the "try by ID, then by name" logic. It seems in the impl for `Message`, it's doing an explicit `println!` on the returned message while converting it (presumably as part of the error handling logic) on https://github.com/dtantsur/rust-osauth/blob/0.4.2/src/client.rs#L188

Is this `println!` on purpose, or was it just left accidentally while debugging the code?

**Comment by dtantsur** [comment]
@milliams whooops. No, I'm quite sure any `println!` (at least two in that function) is accidental.
