### ISSUE TITLE
Error handling in DetailedServerQuery

### ISSUE THREAD

**Issue by sd109** [dtantsur/rust-openstack#146]
When running a detailed server query, the batching behaviour of `fetch_chunk` makes error handling difficult. I'm trying to run the following code
```rust
let results = cloud
    .find_servers()
    .detailed()
    .into_stream()
    .collect::<Vec<openstack::Result<Server>>>()
    .await;
```
and expect to have 81 Server objects returned to me based on the cloud I'm testing against. The problem is that my target cloud is a multi-user dev environment which has seen a lot of experimentation and as a result some of the server queries return errors. For example, running
```rust
let server_summaries = cloud.list_servers().await.unwrap();
for ss in server_summaries {
    let result = cloud.get_server(ss.id()).await;
    if result.is_err() {
            println!("{e}");
    }
}
```
gives me 3 errors of the form
```
Normal Flavor e081ba5c-90a8-4f8f-abc4-d262cecf55dc could not be found.
Requested resource was not found: Flavor with given name or ID not found
```
From an openstack perspective (I think) what's happening here is that a flavour has been deleted while still having servers using that flavour, but that's not really important. (I also can't work out exactly where the query for flavours by ID is happening in this library, maybe it's done by the OpenStack API as part of the server details request, but I don't think that's relevant to the wider issue either.)

The problem is that the `results` variable in the first code snippet returns a vector of 51 elements where the first 50 are `Ok` and the final element is `Err`. However, if I add a `.with_limit(77)` to the query I get a vec of 77 `Ok` values but `.with_limit(78)` gives me a vec of length 1 with a single `Err` (because the 78th server in the list is the first that has a broken flavour reference, so with no limit the first chunk of 50 servers are fetched successfully then the second chunk returns the error).

Am I missing some simple way to return each item from the stream and handle each error separately? Or maybe there needs to be some more explicit error handling in the [list_servers_detailed](https://github.com/dtantsur/rust-openstack/blob/137e340ce07b55c3391ad650ad9fd729a50f4fd5/src/compute/api.rs#L292) function to accommodate this?

**Comment by dtantsur** [comment]
Hi! These all are good questions. I haven't put any thoughts into the question "what if some of the resources are not retrievable". Frankly, I suspect your case is somewhat unusual. I also think the behavior you're describing is somewhat forced on me by how the asynchronous code and streams work in Rust. I'll take a look and let you know what I think.
