### ISSUE TITLE
Setup CI via OpenLab

### ISSUE THREAD

**Issue by mrhillsman** [dtantsur/rust-openstack#15]
Hey @dtantsur 

Opening this issue to start working with you on getting this SDK added to utilize OpenLab resources.

**Comment by dtantsur** [comment]
Awesome, thanks! Let's work on it.

**Comment by mrhillsman** [comment]
In addition to #16 the Github app will need to be installed - https://github.com/apps/theopenlab-ci

**Comment by dtantsur** [comment]
The app is installed for this repo.

**Comment by mrhillsman** [comment]
@dtantsur successfully triggered ci: https://github.com/dtantsur/rust-openstack/pull/17
job definition within the playbooks directory and updating the .zuul.yaml configuration to run defined jobs is the next step. more details can be found in the zuul documentation and we are available to assist where we can. @liu-sheng @animationzl and @kiwik a part of the OpenLab team as well and work out of China. also i highly recommend joining #askopenlab on freenode
