### ISSUE TITLE
Implement Router API

### ISSUE THREAD

**Issue by dtantsur** [dtantsur/rust-openstack#60]

**Comment by mchlumsky** [comment]
I've been working on this. Should have a MR some time this week.

**Comment by mchlumsky** [comment]
#117

**Comment by mchlumsky** [comment]
@dtantsur I am still working on the follow-up MR. Got a few commits done. If this is blocking a release (as I suspect it might) I can do a MR for what I have done already.

**Comment by dtantsur** [comment]
@mchlumsky I'm not in a hurry, but I'd rather prefer several pull requests just to make reviewing easier. Up to you in the end.

**Comment by mchlumsky** [comment]
PRs: #119 #120 #121 #122 #123

**Comment by dtantsur** [comment]
Thank you @mchlumsky, great job with this feature!
