### ISSUE TITLE
Add support of object storage

### ISSUE THREAD

**Issue by bnjjj** [dtantsur/rust-openstack#91]
Could be great to have implementation of swift object storage

**Comment by dtantsur** [comment]
It's totally on my radar (and contributions are welcome). For now you can use the more low-level rust-osauth, e.g. https://github.com/dtantsur/rust-osauth/blob/master/examples/object-store.rs

**Comment by dtantsur** [comment]
https://github.com/dtantsur/rust-openstack/pull/100

**Comment by dtantsur** [comment]
Basic support implemented, please open more issues for missing functionality.

**Comment by bnjjj** [comment]
Thanks guy ! You rocks ! I'll try this in next days

**Comment by dtantsur** [comment]
@bnjjj please let me know how it goes :)
